### ISSUE TITLE
Install fails on heroku

### ISSUE THREAD

**Issue by karlperemil** [ofa/connect#20]
Following the setup guide:

http://opendocs.ofaconnect.com/en/latest/dev/deploying/heroku_setup.html

At first the push to Heroku failed due to the amazon s3 bucket not being a US Standard region (I used Ireland). Switching to US Standard region solved the problem.

Then the build failed on npm install on phantom.js.

Running it again (as suggested by the setup guide) it worked.

Now it fails on 
'python manage.py collectstatic --noinput'

Full log:
Hello! It looks like your application is using an outdated version of Python.
remote:  !     This caused the security warning you saw above during the 'pip install' step.
remote:  !     We recommend 'python-2.7.11', which you can specify in a 'runtime.txt' file.
remote:  !       -- Much Love, Heroku.
remote:
remote:      $ python manage.py collectstatic --noinput
remote:        /app/.heroku/python/lib/python2.7/site-packages/environ/environ.py:524: UserWarning: not reading .env - it doesn't exist.
remote:          warnings.warn("not reading %s - it doesn't exist." % env_file)
remote:        Traceback (most recent call last):
remote:          File "manage.py", line 11, in <module>
remote:            execute_from_command_line(sys.argv)
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
remote:            utility.execute()
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
remote:            self.fetch_command(subcommand).run_from_argv(self.argv)
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
remote:            self.execute(*args, **cmd_options)
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
remote:            output = self.handle(*args, **options)
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
remote:            collected = self.collect()
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 98, in collect
remote:            for path, storage in finder.list(self.ignore_patterns):
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 112, in list
remote:            for path in utils.get_files(storage, ignore_patterns):
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/utils.py", line 28, in get_files
remote:            directories, files = storage.listdir(location)
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/core/files/storage.py", line 300, in listdir
remote:            for entry in os.listdir(path):
remote:        OSError: [Errno 2] No such file or directory: '/app/bower_components'
remote:
remote:  !     Error while running '$ python manage.py collectstatic --noinput'.
remote:        See traceback above for details.
remote:
remote:        You may need to update application code to resolve this error.
remote:        Or, you can disable collectstatic for this application:
remote:
remote:           $ heroku config:set DISABLE_COLLECTSTATIC=1
remote:
remote:        https://devcenter.heroku.com/articles/django-assets
remote:
remote:  !     Push rejected, failed to compile Multipack app

**Comment by nickcatal** [comment]
Per the instructions, you need to have the bower components available before you can run grunt and compile.

For awhile I had it include the bower components and run grunt during the compile step, but loading bower components can take quite awhile.

This command (from the readme) should work:

```bash
# Download, compile, and deploy static assets to S3.
# This could take a bit.
heroku run 'bower install --config.interactive=false;grunt prep;python manage.py collectstatic --noinput'
```

I haven't tried with non US-Standard S3.

**Comment by nickcatal** [comment]
Sorry, try `heroku config:set DISABLE_COLLECTSTATIC=1`

It appears that heroku/heroku-buildpack-python#273 broke the "When `collectstatic` fails on build print to the log that it failed but do not fail the build" functionality that we were relying on.

I'll add that to our documentation.

**Comment by karlperemil** [comment]
@nickcatal 

`heroku config:set DISABLE_COLLECTSTATIC=1` worked fine, thank you.

`heroku run python manage.py migrate` ran without issue.

`heroku run 'bower install --config.interactive=false;grunt prep;python manage.py collectstatic --noinput'`shows some warnings:

```bower checkout      jquery-oembed-all#master
TypeError: LRU: key must be a string or number. Almost certainly a bug! undefined
    at typeCheckKey (/app/node_modules/lru-cache/lib/lru-cache.js:20:19)
    at LRUCache.get (/app/node_modules/lru-cache/lib/lru-cache.js:230:3)
    at /app/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:122:70
    at _fulfilled (/app/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/app/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:796:13)
    at /app/node_modules/q/q.js:857:14
    at runSingle (/app/node_modules/q/q.js:137:13)
    at flush (/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)```

and

```bootstrap#3.3.5 bower_components/bootstrap
└── jquery#1.11.1
{ [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }```

But in the end it returns `Done, without errors.`


However after everything is deployed the app displays Internal Server Error in the browser.

Heroku logs show this:

2016-04-04T12:41:20.130646+00:00 heroku[router]: at=info method=GET path="/" host=ra-connect.herokuapp.com request_id=655a9ab7-7c17-4bf8-89f6-ebffc053ee19 fwd="83.241.168.188" dyno=web.1 connect=0ms service=10ms status=500 bytes=290
2016-04-04T12:41:20.398236+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=ra-connect.herokuapp.com request_id=5123ba32-220a-408d-b7d1-443e863de395 fwd="83.241.168.188" dyno=web.1 connect=0ms service=10ms status=500 bytes=290
2016-04-04T12:41:20.135974+00:00 app[web.1]: 2016-04-04 08:41:20 [41] [ERROR] Error handling request
2016-04-04T12:41:20.136004+00:00 app[web.1]: Traceback (most recent call last):
2016-04-04T12:41:20.136006+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/async.py", line 45, in handle
2016-04-04T12:41:20.136007+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2016-04-04T12:41:20.136008+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 151, in handle_request
2016-04-04T12:41:20.136008+00:00 app[web.1]:     super(GeventWorker, self).handle_request(*args)
2016-04-04T12:41:20.136009+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/async.py", line 93, in handle_request
2016-04-04T12:41:20.136010+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2016-04-04T12:41:20.136010+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
2016-04-04T12:41:20.136011+00:00 app[web.1]:     response = self.get_response(request)
2016-04-04T12:41:20.136011+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
2016-04-04T12:41:20.136012+00:00 app[web.1]:     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
2016-04-04T12:41:20.136013+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
2016-04-04T12:41:20.136013+00:00 app[web.1]:     if resolver.urlconf_module is None:
2016-04-04T12:41:20.136014+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
2016-04-04T12:41:20.136015+00:00 app[web.1]:     self._urlconf_module = import_module(self.urlconf_name)
2016-04-04T12:41:20.136015+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2016-04-04T12:41:20.136016+00:00 app[web.1]:     __import__(name)
2016-04-04T12:41:20.136017+00:00 app[web.1]:   File "/app/connect/urls.py", line 12, in <module>
2016-04-04T12:41:20.136017+00:00 app[web.1]:     from django_bouncy.views import endpoint as bouncy_endpoint
2016-04-04T12:41:20.136018+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django_bouncy/views.py", line 15, in <module>
2016-04-04T12:41:20.136018+00:00 app[web.1]:     from django_bouncy.utils import (
2016-04-04T12:41:20.136019+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django_bouncy/utils.py", line 21, in <module>
2016-04-04T12:41:20.136021+00:00 app[web.1]:     import pem
2016-04-04T12:41:20.136021+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pem/__init__.py", line 4, in <module>
2016-04-04T12:41:20.136022+00:00 app[web.1]:     from . import twisted
2016-04-04T12:41:20.136023+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pem/twisted.py", line 11, in <module>
2016-04-04T12:41:20.136024+00:00 app[web.1]:     from OpenSSL.SSL import FILETYPE_PEM
2016-04-04T12:41:20.136024+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
2016-04-04T12:41:20.136024+00:00 app[web.1]:     from OpenSSL import rand, crypto, SSL
2016-04-04T12:41:20.136025+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
2016-04-04T12:41:20.136025+00:00 app[web.1]:     from OpenSSL._util import (
2016-04-04T12:41:20.136026+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
2016-04-04T12:41:20.136027+00:00 app[web.1]:     from cryptography.hazmat.bindings.openssl.binding import Binding
2016-04-04T12:41:20.136027+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 88, in <module>
2016-04-04T12:41:20.136028+00:00 app[web.1]:     error=-1)
2016-04-04T12:41:20.136028+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 77, in wrapper
2016-04-04T12:41:20.136029+00:00 app[web.1]:     ffi.def_extern(name=name, **kwargs)(func)
2016-04-04T12:41:20.136029+00:00 app[web.1]: AttributeError: 'CompiledFFI' object has no attribute 'def_extern'
2016-04-04T12:41:20.137404+00:00 app[web.1]: measure#nginx.service=0.010 request_id=655a9ab7-7c17-4bf8-89f6-ebffc053ee19
2016-04-04T12:41:20.403580+00:00 app[web.1]: 2016-04-04 08:41:20 [41] [ERROR] Error handling request
2016-04-04T12:41:20.403588+00:00 app[web.1]: Traceback (most recent call last):
2016-04-04T12:41:20.403589+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/async.py", line 45, in handle
2016-04-04T12:41:20.403590+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2016-04-04T12:41:20.403590+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 151, in handle_request
2016-04-04T12:41:20.403591+00:00 app[web.1]:     super(GeventWorker, self).handle_request(*args)
2016-04-04T12:41:20.403591+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/async.py", line 93, in handle_request
2016-04-04T12:41:20.403612+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2016-04-04T12:41:20.403613+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
2016-04-04T12:41:20.403614+00:00 app[web.1]:     response = self.get_response(request)
2016-04-04T12:41:20.403615+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
2016-04-04T12:41:20.403616+00:00 app[web.1]:     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
2016-04-04T12:41:20.403617+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
2016-04-04T12:41:20.403618+00:00 app[web.1]:     if resolver.urlconf_module is None:
2016-04-04T12:41:20.403618+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
2016-04-04T12:41:20.403619+00:00 app[web.1]:     self._urlconf_module = import_module(self.urlconf_name)
2016-04-04T12:41:20.403620+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2016-04-04T12:41:20.403620+00:00 app[web.1]:     __import__(name)
2016-04-04T12:41:20.403621+00:00 app[web.1]:   File "/app/connect/urls.py", line 12, in <module>
2016-04-04T12:41:20.403622+00:00 app[web.1]:     from django_bouncy.views import endpoint as bouncy_endpoint
2016-04-04T12:41:20.403622+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django_bouncy/views.py", line 15, in <module>
2016-04-04T12:41:20.403623+00:00 app[web.1]:     from django_bouncy.utils import (
2016-04-04T12:41:20.403624+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django_bouncy/utils.py", line 21, in <module>
2016-04-04T12:41:20.403625+00:00 app[web.1]:     import pem
2016-04-04T12:41:20.403625+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pem/__init__.py", line 4, in <module>
2016-04-04T12:41:20.403626+00:00 app[web.1]:     from . import twisted
2016-04-04T12:41:20.403627+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pem/twisted.py", line 11, in <module>
2016-04-04T12:41:20.403627+00:00 app[web.1]:     from OpenSSL.SSL import FILETYPE_PEM
2016-04-04T12:41:20.403628+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
2016-04-04T12:41:20.403628+00:00 app[web.1]:     from OpenSSL import rand, crypto, SSL
2016-04-04T12:41:20.403629+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
2016-04-04T12:41:20.403630+00:00 app[web.1]:     from OpenSSL._util import (
2016-04-04T12:41:20.403630+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
2016-04-04T12:41:20.403631+00:00 app[web.1]:     from cryptography.hazmat.bindings.openssl.binding import Binding
2016-04-04T12:41:20.403632+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 88, in <module>
2016-04-04T12:41:20.403632+00:00 app[web.1]:     error=-1)
2016-04-04T12:41:20.403633+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 77, in wrapper
2016-04-04T12:41:20.403634+00:00 app[web.1]:     ffi.def_extern(name=name, **kwargs)(func)
2016-04-04T12:41:20.403635+00:00 app[web.1]: AttributeError: 'CompiledFFI' object has no attribute 'def_extern'
2016-04-04T12:41:20.405013+00:00 app[web.1]: measure#nginx.service=0.009 request_id=5123ba32-220a-408d-b7d1-443e863de395


---

and

---

2016-04-04T12:13:03.877641+00:00 app[scheduler.1]: IOError: Socket closed
2016-04-04T12:13:43.555357+00:00 app[web.1]: 2016-04-04 12:13:43.555 23 LOG Stats: 0 req/s, in 0 b/s, out 0 b/s,query 0 us
2016-04-04T12:14:01.564055+00:00 app[scheduler.1]: 2016-04-04 12:14:01.563 22 LOG Stats: 0 req/s, in 0 b/s, out 0 b/s,query 0 us
2016-04-04T12:14:33.963451+00:00 app[scheduler.1]: [2016-04-04 08:14:33,962: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
2016-04-04T12:14:33.963461+00:00 app[scheduler.1]: Traceback (most recent call last):
2016-04-04T12:14:33.963462+00:00 app[scheduler.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/celery/worker/consumer.py", line 279, in start
2016-04-04T12:14:33.963463+00:00 app[scheduler.1]:     blueprint.start(self)
2016-04-04T12:14:33.963464+00:00 app[scheduler.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
2016-04-04T12:14:33.963465+00:00 app[scheduler.1]:     step.start(parent)
2016-04-04T12:14:33.963465+00:00 app[scheduler.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/celery/worker/consumer.py", line 838, in start
2016-04-04T12:14:33.963466+00:00 app[scheduler.1]:     c.loop(*c.loop_args())
2016-04-04T12:14:33.963467+00:00 app[scheduler.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/celery/worker/loops.py", line 76, in asynloop
2016-04-04T12:14:33.963468+00:00 app[scheduler.1]:     next(loop)
2016-04-04T12:14:33.963468+00:00 app[scheduler.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/async/hub.py", line 279, in create_loop
2016-04-04T12:14:33.963469+00:00 app[scheduler.1]:     item()
2016-04-04T12:14:33.963470+00:00 app[scheduler.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/utils.py", line 42, in __call__
2016-04-04T12:14:33.963471+00:00 app[scheduler.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/utils.py", line 39, in __call__
2016-04-04T12:14:33.963470+00:00 app[scheduler.1]:     self.set_error_state(exc)
2016-04-04T12:14:33.963472+00:00 app[scheduler.1]:     **dict(self.kwargs, **kwargs) if self.kwargs else kwargs
2016-04-04T12:14:33.963473+00:00 app[scheduler.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
2016-04-04T12:14:33.963502+00:00 app[scheduler.1]:     return self.transport.drain_events(self.connection, **kwargs)
2016-04-04T12:14:33.963504+00:00 app[scheduler.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 95, in drain_events
2016-04-04T12:14:33.963508+00:00 app[scheduler.1]:     return connection.drain_events(**kwargs)
2016-04-04T12:14:33.963511+00:00 app[scheduler.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 303, in drain_events
2016-04-04T12:14:33.963512+00:00 app[scheduler.1]:     chanmap, None, timeout=timeout,
2016-04-04T12:14:33.963513+00:00 app[scheduler.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 366, in _wait_multiple
2016-04-04T12:14:33.963513+00:00 app[scheduler.1]:     channel, method_sig, args, content = read_timeout(timeout)
2016-04-04T12:14:33.963514+00:00 app[scheduler.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 330, in read_timeout
2016-04-04T12:14:33.963518+00:00 app[scheduler.1]:     return self.method_reader.read_method()
2016-04-04T12:14:33.963519+00:00 app[scheduler.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
2016-04-04T12:14:33.963520+00:00 app[scheduler.1]:     raise m

**Comment by nickcatal** [comment]
For ``web`` I noticed ``AttributeError: 'CompiledFFI' object has no attribute 'def_extern'`` this weekend (which is new.) Somewhat inconvenient this is when I notice it, but it is what it is.

Can you double check and make sure you're on ae282934667b8fcfa31714c4edfc9a485dc31c7d ?

As for the task queue traceback, it should still be working fine, it's just timing out every so often and having to reconnect with that ugly traceback appearing in the logs. No tasks should be getting lost. I'm seeing this on my free version of Connect but not on my public demo (which has a paid AMQP account), so I'll start a ticket with Heroku & the AMQP addon provider I'm using.

**Comment by karlperemil** [comment]
I was not on ae28293. Thank you, works now!
