### ISSUE TITLE
UserWarning: not reading .env - it doesn't exist.

### ISSUE THREAD

**Issue by mgifford** [ofa/connect#22]
Stumbled over the next step unfortunately. This is for the local python I assume. Python is running locally, but I haven't specified a port for this. Not sure what is wrong with the migration. 

`$ heroku run python manage.py migrate
Running python manage.py migrate on oc2-connect.... up, run.7636
Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
Recommending WEB_CONCURRENCY=1
/app/.heroku/python/lib/python2.7/site-packages/environ/environ.py:524: UserWarning: not reading .env - it doesn't exist.
  warnings.warn("not reading %s - it doesn't exist." % env_file)
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 19, in <module>
    from django.db.migrations.autodetector import MigrationAutodetector
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 13, in <module>
    from django.db.migrations.questioner import MigrationQuestioner
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/questioner.py", line 12, in <module>
    from .loader import MIGRATIONS_MODULE_NAME
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/loader.py", line 10, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 9, in <module>
    class MigrationRecorder(object):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 23, in MigrationRecorder
    class Migration(models.Model):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 24, in Migration
    app = models.CharField(max_length=255)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1081, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 161, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/app/connect/settings/__init__.py", line 24, in <module>
    from .base_settings import *
  File "/app/connect/settings/base_settings.py", line 87, in <module>
    default_cache = env.cache()
  File "/app/.heroku/python/lib/python2.7/site-packages/environ/environ.py", line 188, in cache_url
    return self.cache_url_config(self.url(var, default=default), backend=backend)
  File "/app/.heroku/python/lib/python2.7/site-packages/environ/environ.py", line 173, in url
    return self.get_value(var, cast=urlparse.urlparse, default=default, parse_default=True)
  File "/app/.heroku/python/lib/python2.7/site-packages/environ/environ.py", line 250, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the CACHE_URL environment variable
`

**Comment by nickcatal** [comment]
When running locally you have 2 options for configuration:
- Actually set all the key variables in your environment (do this in deployment)
- Configure a `.env` file with key/value pairs, which will be loaded into your environment at runtime ([details here](http://opendocs.ofaconnect.com/en/latest/dev/developing/environment_setup.html#setting-up-a-env-file))
(you could also mix these up if you want)

If we don't have a ``.env`` file, but still have all the environment vars, the package that processes the ``.env`` file complains. I'll figure out how to silence or better spell that out.

On Heroku, everything needs to be set via environment variables. So in this case the important line is ``django.core.exceptions.ImproperlyConfigured: Set the CACHE_URL environment variable``

Which memcached provider did you choose when you setup Heroku? Those set a ``CACHE_URL`` environment variable (or something similar to that.) Both [MemCachier](https://elements.heroku.com/addons/memcachier) and [Memcached Cloud](https://elements.heroku.com/addons/memcachedcloud) should work. We use memcachier locally.

**Comment by nickcatal** [comment]
This specific situation (the missing environment file language even though things are perfectly setup) has always been annoying to me so I submitted a pull-request to the original project to make this more clear. joke2k/django-environ#83

Hopefully that makes it in.

**Comment by mgifford** [comment]
I tried setting this with the .env but I couldn't get it to stick.  However, just setting it manually this way seemed to get me past it. 

heroku config:set CACHE_URL=filecache:///Users/mgifford/connect/tmp

**Comment by nickcatal** [comment]
`.env` isn't a file that's tracked in the git repo. It's just a place you can store KEY=VALUE pairs during development instead of constantly adding them to your bash environment. [The Connect documentation describes this more](http://opendocs.ofaconnect.com/en/latest/dev/developing/environment_setup.html#setting-up-a-env-file). On Heroku you actually set the KEY=VALUE using `heroku config:set KEY=VALUE`.

I wouldn't use filecache in this place and instead get one of the memcached providers going.

While `CACHE_URL` is required, Memcachier and Memcache Cloud don't provide you with a `CACHE_URL`. For example, if you have the Memcachier add-on installed and type in `heroku config` you'll see that the addon has inserted `MEMCACHIER_USERNAME`, `MEMCACHIER_SERVERS`, and `MEMCACHIER_PASSWORD` into your configuration. What you won't see (by default) is `CACHE_URL`

Connect will sniff out `MEMCACHIER_USERNAME`, `MEMCACHIER_SERVERS`, and `MEMCACHIER_PASSWORD` and generate a `CACHE_URL` using the data it finds. It's not optimal (it'd be nice if one of the Heroku memcache add-ons just set `CACHE_URL` directly) but it works.

In your case, you're setting `CACHE_URL` on Heroku directly to a filecache. Which is going to cause huge problems later, because Heroku will not persist that file or share it among your workers. I'm surprised Heroku even lets you put a temporary file at `/Users/mgifford/connect/temp`

**Comment by mgifford** [comment]
Ok, so you have to signup with your credit card and then do `heroku addons:create memcachier:dev`

I tried a few options based on what I could figure from CACHE_URL http://opendocs.ofaconnect.com/en/latest/dev/settings.html

I can now see 

MEMCACHIER_OLIVE_PASSWORD: 
MEMCACHIER_OLIVE_SERVERS:  
MEMCACHIER_OLIVE_USERNAME: 
MEMCACHIER_PASSWORD:       
MEMCACHIER_SERVERS:        
MEMCACHIER_USERNAME:       

But I all I still get this error when running `heroku run 'bower install --config.interactive=false;grunt prep;python manage.py collectstatic --noinput'`

Done, without errors.
/app/.heroku/python/lib/python2.7/site-packages/environ/environ.py:524: UserWarning: not reading .env - it doesn't exist.
  warnings.warn("not reading %s - it doesn't exist." % env_file)
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 107, in collect
    handler(path, prefixed_path, storage)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 305, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 218, in delete_file
    if self.storage.exists(prefixed_path):
  File "/app/.heroku/python/lib/python2.7/site-packages/storages/backends/s3boto.py", line 411, in exists
    if self.entries:
  File "/app/.heroku/python/lib/python2.7/site-packages/storages/backends/s3boto.py", line 289, in entries
    for entry in self.bucket.list(prefix=self.location))
  File "/app/.heroku/python/lib/python2.7/site-packages/storages/backends/s3boto.py", line 288, in <genexpr>
    self._entries = dict((self._decode_name(entry.key), entry)
  File "/app/.heroku/python/lib/python2.7/site-packages/boto/s3/bucketlistresultset.py", line 34, in bucket_lister
    encoding_type=encoding_type)
  File "/app/.heroku/python/lib/python2.7/site-packages/boto/s3/bucket.py", line 472, in get_all_keys
    '', headers, **params)
  File "/app/.heroku/python/lib/python2.7/site-packages/boto/s3/bucket.py", line 410, in _get_all
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 301 Moved Permanently
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>example-heroku</Bucket><Endpoint>example-heroku.s3.amazonaws.com</Endpoint><RequestId>long, complicated string</HostId></Error>

**Comment by mgifford** [comment]
I've been looking for resources on `boto.exception.S3ResponseError: S3ResponseError: 301 Moved Permanently` errors and the mostly seem to have to do with being in a different region. 

My S3 bucket says `S3 does not require region selection.` so not sure what this would be about. Tried a few different options, but it's like playing darts blindfolded.

**Comment by nickcatal** [comment]
I've never seen that before.

Double-check that `AWS_STORAGE_BUCKET_NAME` is just the bucket name of a US-Standard bucket.

I'm not 100% sure what it would take to support something other than US Standard. Not something I've spent a ton of time thinking about since by default Heroku is based out of US East. I'll look into it.

**Comment by mgifford** [comment]
My S3 is in Oregon it seems, so setting `AWS_S3_CUSTOM_DOMAIN:        s3-us-west-2.amazonaws.com` seemed to help.

If I'm using memcachier, what should the CACHE_URL be?

Running `heroku addons:docs memcachier` opens up a new browser window. I can deploy an instance to heroku, but then don't know how to connect it back to the CACHE_URL that the code keeps complaining about. 

Sorry for this step-by-step error process.

**Comment by nickcatal** [comment]
I make no guarantees that Oregon will allow media uploads. Let me know if it does!

You don't need a `CACHE_URL` on Heroku.

We use https://github.com/rdegges/django-heroku-memcacheify in https://github.com/ofa/connect/blob/master/connect/settings/base_settings.py#L74-L97

Just having `MEMCACHIER_PASSWORD`, `MEMCACHIER_SERVERS`, and `MEMCACHIER_USERNAME` is enough

So if it detects any of the core Heroku Memcached add-ons, it automatically assigns that add-on.
